[package]
name = "better-auth-hca"
version = "0.1.3"
edition = "2024"
description = "Hack Club Auth integration with the better-auth-rs crate"
repository = "https://github.com/Shuflduf/better-auth-hca"
license = "GPL-3.0-or-later"
keywords = ["auth", "hackclub"]

[dependencies]
better-auth = {
  version = "0.10",
  default-features = false,
  features = ["rustls"]
}
